CREATE TABLE IF NOT EXISTS feedbacks (
  id SERIAL PRIMARY KEY,
  tipo VARCHAR(50) NOT NULL,
  regiao VARCHAR(100) NOT NULL,
  unidade VARCHAR(255) NOT NULL,
  nota INTEGER NOT NULL DEFAULT 0,
  descricao TEXT NOT NULL,
  nome VARCHAR(255),
  telefone VARCHAR(50),
  email VARCHAR(255),
  anonimo BOOLEAN NOT NULL DEFAULT FALSE,
  protocolo VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
